object Icons {
    val arrowDown = "arrow_down.png"
    val edit = "ic_edit.png"
    val chat = "chat.png"
    val directMessage = "dm.png"
    val mention = "mention.png"
    val bookmark = "bookmark.png"
    val caretUp = "caret_up.png"
    val caretDown = "caret_down.png"
    val caretRight = "caret_right.png"
    val hash = "hash.png"
    val verticalDots = "vertical.png"
    val info = "info.png"
    val addPerson = "add_person.png"
    val call = "call.png"
}